name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  page-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.COMMON_KEY }}
          submodules: true
      - name: Add gh-pages as submodule
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.COMMON_KEY }}
          ref: gh-pages
          path: _site
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Cache bundler packages
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-
      - name: Build static site by Jekyll
        run: |
          bundle config path vendor/bundle
          ./dep.sh
          ./build.sh
      - name: Commit & Push
        run: |
          git add .
          git config --global user.name 'GitHub Actions #${{ github.job }} on behalf of ${{ github.actor }}'
          git config --global user.email "me@tinson.dev"
          git commit -am ${{ github.sha }}
          git push
        working-directory: _site
